# --- 1. ????????? ?? ?????? ????? (H2 In-Memory) ---
# DB_CLOSE_DELAY=-1 ?????????, ?? ?????? ???? ?? ?? ?????? ???? ?????? ???????
spring.datasource.url=jdbc:h2:mem:sapdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.generate-unique-name=false

# --- 2. ????????? ?? H2 ????????? ---
# ????????? ??????? ???? ????????
spring.h2.console.enabled=true
# ???????? ?????? ??? (http://localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# --- 3. ????????? ?? HIBERNATE ? ????????????? ---
# ??????? ???????????? SQL ?????? ? ????????? (??????? ?? ?????????)
spring.jpa.show-sql=true

# ???????????, ?? ????????? ?? ?? ???????? ????? DataInitializer-? ?? ??????
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always